const env = require('dotenv').config();

module.exports = {
    VERSION_API_REST: process.env.VERSION_API_REST,
    MONGODB_URL: process.env.MONGODB_URL,
    SECRET_KEY: process.env.SECRET_KEY,
    BCRYPT_SATL: Number(process.env.BCRYPT_SATL),
    CLOUDINARY_API_KEY: process.env.CLOUDINARY_API_KEY,
    CLOUDINARY_API_SECRET: process.env.CLOUDINARY_API_SECRET,
    CLOUDINARY_CLOUD_NAME: process.env.CLOUDINARY_CLOUD_NAME,
    GRAVATAR_URL: process.env.GRAVATAR_URL,
    GMAIL_SERVICE_NAME: process.env.GMAIL_SERVICE_NAME,
    GMAIL_SERVICE_HOST: process.env.GMAIL_SERVICE_HOST,
    GMAIL_SERVICE_SECURE: process.env.GMAIL_SERVICE_SECURE,
    GMAIL_SERVICE_PORT: process.env.GMAIL_SERVICE_PORT,
    GMAIL_USER_NAME: process.env.GMAIL_USER_NAME,
    GMAIL_USER_PASSWORD: process.env.GMAIL_USER_PASSWORD,
    SENDGRID_API_KEY: process.env.SENDGRID_API_KEY,
    PORT: process.env.PORT
}